version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "8000:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data